### ISSUE TITLE
can't library synapser with error : package or namespace load failed for ‘synapser’:

### ISSUE THREAD

**Issue by cqneosun** [Sage-Bionetworks/synapseDocs#785]
> > library("synapser", lib.loc="C:/Program Files/R/R-4.0.0/library")
Error: package or namespace load failed for ‘synapser’:
 loadNamespace()里算'synapser'时.onLoad失败了，详细内容：
  调用: PythonEmbedInR::pyExec("syn=synapseclient.Synapse(skip_checks=True)")
  错误: 
   Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "C:/Program Files/R/R-4.0.0/library/synapser\Lib\site-packages\synapseclient\client.py", line 188, in __init__
       self.cache = cache.Cache(cache_root_dir)
     File "C:/Program Files/R/R-4.0.0/library/synapser\Lib\site-packages\synapseclient\core\cache.py", line 85, in __init__
       self.cache_root_dir = cache_root_dir
     File "C:/Program Files/R/R-4.0.0/library/synapser\Lib\site-packages\synapseclient\core\cache.py", line 79, in __setattr__
       os.makedirs(value)
     File "os.py", line 210, in makedirs
     File "os.py", line 210, in makedirs
     File "os.py", line 220, in makedirs
   OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'D:/360data/????'
In addition: Warning messages:
1: In readChar(f, 2) : can only read in bytes in a non-UTF-8 MBCS locale
2: In readChar(f, 2) : can only read in bytes in a non-UTF-8 MBCS locale
> 

> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C                                                   
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.0        R6_2.4.1              tools_4.0.0           yaml_2.2.1           
[5] codetools_0.2-16      pack_0.1-1            PythonEmbedInR_0.4.65

How can I fix it?Help.

**Comment by cqneosun** [comment]
https://r-docs.synapse.org/articles/troubleshooting.html
I have try but failed.

**Comment by cqneosun** [comment]
> https://r-docs.synapse.org/articles/troubleshooting.html
> I have try but failed.

.libPaths()
[1] "C:/Program Files/R/R-4.0.0/library"

**Comment by jkiang13** [comment]
Hi @cqneosun,

Can you try the following? This appears to be an issue with R on Windows and usernames with unicode characters in them. 

Open a command prompt
1. Run the following command:
```set HOME```
Confirm that there is no “HOME” variable (other variables such as HOMEDRIVE and HOMEPATH may be already be set).
2. If there is no HOME environment variable, set one as follows:
```setx HOME %USERPROFILE%\Documents```
<img width="983" alt="Screen Shot 2020-06-16 at 03 28 39" src="https://user-images.githubusercontent.com/2145855/84764284-5121cb80-af82-11ea-8bca-1db279452473.png">
3. Close the command prompt, and open a new command prompt and confirm that there is now a HOME environment variable set by running the ```set HOME``` command again. It should now show a variable.
<img width="977" alt="Screen Shot 2020-06-16 at 03 34 52" src="https://user-images.githubusercontent.com/2145855/84764473-a231bf80-af82-11ea-9e4d-c29fc1af6821.png">
4. Now restart R and attempt to load the library as before:
```library("synapser", lib.loc="C:/Program Files/R/R-4.0.0/library")```


If you can confirm that it resolves the issue we may be able to fix this without the above being necessary in a future version.

Thanks!

**Comment by cqneosun** [comment]
Thanks for your generous help.I figure it out.
