### ISSUE TITLE
Unable to build site

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#81]
lillen:synapseDocs>bundle exec jekyll  serve --incremental
Configuration file: /Users/lom/Dropbox/Sage/synapseDocs/_config.yml
            Source: .
       Destination: ./_site
 Incremental build: enabled
      Generating... 
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'chance' from '/Users/lom/Dropbox/Sage/synapseDocs/js'
    at /Users/lom/Dropbox/Sage/synapseDocs/node_modules/resolve/lib/async.js:46:17
    at process (/Users/lom/Dropbox/Sage/synapseDocs/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/lom/Dropbox/Sage/synapseDocs/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/lom/Dropbox/Sage/synapseDocs/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/lom/Dropbox/Sage/synapseDocs/node_modules/resolve/lib/async.js:92:31)
    at /Users/lom/Dropbox/Sage/synapseDocs/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
  Conversion error: Jekyll::BrowserifyConverter encountered an error while converting '/js/all.js':
                    end of file reached
jekyll 3.1.2 | Error:  end of file reached

**Comment by larssono** [comment]
Can't reproduce anymore
